sonata_admin:
    title: 'Youcycle Dashboard'
    title_logo : /bundles/sonataadmin/logo.png
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left}
#            - { type: sonata.admin.block.admin_list, position: left, content: {%listeadimin%}}

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
